language: python
python:
 - 2.6
 - 2.7
 - 3.4
 - 3.6
 - pypy
install:
 - python setup.py develop
 - pip install coveralls hacking
 - mkdir local_cache
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
 - SC2READER_CACHE_DIR=local_cache coverage run --source=sc2reader test_replays/test_all.py
 - SC2READER_CACHE_DIR=local_cache coverage run --source=sc2reader --append test_s2gs/test_all.py
after_success:
 - coveralls
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#sc2reader"
